/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './busy.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from 'angular2-dynamic-component/DynamicComponentModule';
import * as import4 from '@angular/common/src/localization';
import * as import5 from 'angular2-dynamic-component/DynamicCache';
import * as import6 from './busy.service';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from './busy.component.ngfactory';
import * as import9 from './busy-backdrop.component.ngfactory';
import * as import10 from '@angular/core/src/i18n/tokens';
import * as import11 from '@angular/core/src/zone/ng_zone';
import * as import12 from './busy-config';
class BusyModuleInjector extends import0.NgModuleInjector<import1.BusyModule> {
  _CommonModule_0:import2.CommonModule;
  _DynamicComponentModule_1:import3.DynamicComponentModule;
  _BusyModule_2:import1.BusyModule;
  __NgLocalization_3:import4.NgLocaleLocalization;
  __DynamicCache_4:import5.DynamicCache;
  __DynamicExtraModules_5:any;
  __BusyService_6:import6.BusyService;
  constructor(parent:import7.Injector) {
    super(parent,[
      import8.BusyComponentNgFactory,
      import9.BusyBackdropComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_3():import4.NgLocaleLocalization {
    if ((this.__NgLocalization_3 == null)) { (this.__NgLocalization_3 = new import4.NgLocaleLocalization(this.parent.get(import10.LOCALE_ID))); }
    return this.__NgLocalization_3;
  }
  get _DynamicCache_4():import5.DynamicCache {
    if ((this.__DynamicCache_4 == null)) { (this.__DynamicCache_4 = new import5.DynamicCache(this.parent.get(import11.NgZone))); }
    return this.__DynamicCache_4;
  }
  get _DynamicExtraModules_5():any {
    if ((this.__DynamicExtraModules_5 == null)) { (this.__DynamicExtraModules_5 = ([] as any[])); }
    return this.__DynamicExtraModules_5;
  }
  get _BusyService_6():import6.BusyService {
    if ((this.__BusyService_6 == null)) { (this.__BusyService_6 = new import6.BusyService(this.parent.get(import12.BusyConfig,(null as any)))); }
    return this.__BusyService_6;
  }
  createInternal():import1.BusyModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._DynamicComponentModule_1 = new import3.DynamicComponentModule();
    this._BusyModule_2 = new import1.BusyModule();
    return this._BusyModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.DynamicComponentModule)) { return this._DynamicComponentModule_1; }
    if ((token === import1.BusyModule)) { return this._BusyModule_2; }
    if ((token === import4.NgLocalization)) { return this._NgLocalization_3; }
    if ((token === import5.DynamicCache)) { return this._DynamicCache_4; }
    if ((token === 'DynamicExtraModules')) { return this._DynamicExtraModules_5; }
    if ((token === import6.BusyService)) { return this._BusyService_6; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const BusyModuleNgFactory:import0.NgModuleFactory<import1.BusyModule> = new import0.NgModuleFactory(BusyModuleInjector,import1.BusyModule);